apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  annotation:
    nbb: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/yoheinbb/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
