apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  annotations:
    argocd.argoproj.io/sync-wave: "999" 
    nbbtest: "2"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/httpd1
    repoURL: https://github.com/yoheinbb/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: false
