apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: httpd1
    repoURL: https://github.com/yoheinbb/argocd-example-apps.git
    targetRevision: main
  syncPolicy:
    automated: {}
